# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img_imu_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12img_imu_data.proto\"z\n\x07ImuData\x12\r\n\x05\x61\x63\x63_x\x18\x01 \x01(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x02 \x01(\x02\x12\r\n\x05\x61\x63\x63_z\x18\x03 \x01(\x02\x12\r\n\x05\x61ng_x\x18\x04 \x01(\x02\x12\r\n\x05\x61ng_y\x18\x05 \x01(\x02\x12\r\n\x05\x61ng_z\x18\x06 \x01(\x02\x12\x15\n\rimu_timestamp\x18\x07 \x01(\x02\"#\n\x07ImgData\x12\x18\n\x10\x63\x61mera_timestamp\x18\x01 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'img_imu_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMUDATA']._serialized_start=22
  _globals['_IMUDATA']._serialized_end=144
  _globals['_IMGDATA']._serialized_start=146
  _globals['_IMGDATA']._serialized_end=181
# @@protoc_insertion_point(module_scope)
