/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_IMU_DATA_PB_H_INCLUDED
#define PB_IMU_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ImuData {
    float acc_x;
    float acc_y;
    float acc_z;
} ImuData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ImuData_init_default                     {0, 0, 0}
#define ImuData_init_zero                        {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ImuData_acc_x_tag                        1
#define ImuData_acc_y_tag                        2
#define ImuData_acc_z_tag                        3

/* Struct field encoding specification for nanopb */
#define ImuData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_x,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_y,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_z,             3)
#define ImuData_CALLBACK NULL
#define ImuData_DEFAULT NULL

extern const pb_msgdesc_t ImuData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ImuData_fields &ImuData_msg

/* Maximum encoded size of messages (where known) */
#define IMU_DATA_PB_H_MAX_SIZE                   ImuData_size
#define ImuData_size                             15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
